In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("bank_customers.csv")

In [3]:
df.head()

,age,job_satisfaction,balance,duration_last_call,num_contacts_last_month,has_housing_loan,has_personal_loan,communication_type,days_since_last_contact,campaign_response_score,subscribed
0,-0.377957,1.043895,1.043494,-0.101838,-1.617442,0.402713,0.913601,-0.067192,0.175471,-1.049646,0
1,-0.325259,1.276263,-0.686123,-2.463205,-0.489426,-0.240715,-1.469496,1.006633,-0.833692,0.957744,0
2,0.739019,-0.600903,-0.177294,1.335714,-0.817332,-0.790047,1.457365,-0.218981,0.878643,-1.257740,0
3,0.474312,-1.103002,1.189936,-0.800186,0.912377,-0.406451,-1.130950,1.985111,1.379029,1.041768,1
4,0.927365,1.114796,0.080284,1.261064,0.761179,0.921563,0.440832,0.184645,-1.567739,-0.142107,1


#### bu data seti hazir bir data seti. Scale edilmis ,non degerler olmayan calismaya hazir ama gerceklige uygundur

### burdaki hedef column "subscribed". Yani bir kampanya var hangi musteriler buna katilim saglicak mi saglamicak mi bunu ogrenmek isteyebiliriz:

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   age                      1000 non-null   float64
 1   job_satisfaction         1000 non-null   float64
 2   balance                  1000 non-null   float64
 3   duration_last_call       1000 non-null   float64
 4   num_contacts_last_month  1000 non-null   float64
 5   has_housing_loan         1000 non-null   float64
 6   has_personal_loan        1000 non-null   float64
 7   communication_type       1000 non-null   float64
 8   days_since_last_contact  1000 non-null   float64
 9   campaign_response_score  1000 non-null   float64
 10  subscribed               1000 non-null   int64  
dtypes: float64(10), int64(1)
memory usage: 86.1 KB


In [5]:
X=df.drop("subscribed", axis=1)
y=df["subscribed"]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.3, random_state=15)

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
logistic =LogisticRegression() #normalde verebilecegimiz cok parametre vardir ama suanlik vermicez
logistic.fit(X_train, y_train)
y_pred=logistic.predict(X_test)

In [9]:
y_pred #gordugumuz gibi predict'ler 0 ve 1'lerden olusuyor

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1])

In [10]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#bu recall, f1, precissions skoru gibi degerler geliyor "classification_report"un icerisinde

In [11]:
score = accuracy_score(y_pred, y_test)
print("score: ", score,"\n")

print(classification_report(y_test, y_pred))

print("confusion_matrix: \n",confusion_matrix(y_test, y_pred))

score:  0.92 

              precision    recall  f1-score   support

           0       0.91      0.92      0.92       145
           1       0.93      0.92      0.92       155

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

confusion_matrix: 
 [[134  11]
 [ 13 142]]


# Hyper Parameter Tuning

### LogisticRegression() sift+tab yaparsak icerisinde bircok parametre cikacaktir.<br>-*-__penalty__: "l2", "l1", "elasticnet" veya "none" seceneklerinden biri kullanilabilir. l2->ridge, l1->lasso degerlerini hatirlarsin. default olarak "l2" kullanilir. Ucunu de denicez biz-*-<br><br>-*-__C__: regularizatin strenght yani ridge, lasso'daki __lambda(alpha)__ degeridir. Default 1'dir. biz 100,10,1,0.1,0.01 degerlerini denicez. En uygun senaryo hangi degerde cikacak ona bakacagiz-*-<br><br>-*-__solver__:  optimizasyon algoritmasini belirlemek icin kullanilir. loss-function'un min degerini bulmak icin matematiksel bir yontem uygular. Solver parametresi, modelin en iyi performansi elde etmesi icin parametreleri (agirliklari) nasil bulacagini belirleyen optimizasyon algoritmasidir.  solver bir modelin __ne__ yapacağını değil, __nasıl__ yapacağını belirleyen mekanizmadır. Biz butun seceneklerini kullanacagiz. Asagida mevcuttur

[Scikit-Learn/Logistic_Regression Dokumantasyonuna gitmek icin tiklayin](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)

In [12]:
model = LogisticRegression() 

In [13]:
penaltilar = ["l1", "l2", "elasticnet"]
c_values=[100, 10, 1, 0.1, 0.01]
solvers = ["newton-cg", "libliner", "lbfgs", "sag", "saga", "newton-cholesky"]

#bunlar en onemli parametrelerdir. yukarida istenirse gidilecek link mevcuttur

### biz bunlari grid_search kutuphanesini kullanmak icin dict tipine donusturmemiz gerekiyor cunku o kutuphane oyle istiyor

In [14]:
parametreler = dict(penalty=penaltilar, C=c_values, solver=solvers)

In [15]:
parametreler

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1, 0.1, 0.01],
 'solver': ['newton-cg',
  'libliner',
  'lbfgs',
  'sag',
  'saga',
  'newton-cholesky']}

# Grid Search CV

### bir model için en iyi hiperparametreleri bulmamıza yardımcı olur. <br> adından da anlaşıldığı gibi, belirlediğiniz hiperparametre değerlerinin bir "ızgarasını" (grid) oluşturur ve bu ızgaradaki her kombinasyonu deneyerek en iyi kombinasyonu bulmaya çalışır. <br><br>Grid Search CV, manuel olarak hiperparametreleri tek tek denemekten çok daha verimlidir. Elle deneme yapmak hem zaman alır hem de en iyi kombinasyonu bulma garantisi vermez. Grid Search, sistematik bir şekilde tüm olası kombinasyonları deneyerek en iyi sonucu bulmanızı sağlar ve bu süreç otomatiktir.

## StratifiedKFold

### StratifiedKFold'un temel amacı, veri setini bölerken her bir alt kümede (fold) sınıf dağılımını korumaktır. Bu, özellikle veri setinizdeki sınıfların dengesiz olduğu durumlarda hayati önem taşır. <br><br>StratifiedKFold, veri setini k adet alt kümeye bölerken, her bir alt kümenin orijinal veri setindeki sınıf oranlarını yansıtmasını sağlar.<br><br>mesela Elinizde 1000 örnekten oluşan bir veri seti var.  Sınıf A: 900 örnek (%90).  Sınıf B: 100 örnek (%10) <br><br>__KFold (Standart Bölme):__ Veriyi rastgele 5 parçaya bölerseniz, bir veya iki parçada hiç Sınıf B örneği olmayabilir. Bu, modelin eğitimini ve testini olumsuz etkiler.<br><br>__StratifiedKFold (Katmanlı Bölme):__ Veriyi 5 parçaya bölerken, her bir parçada yaklaşık 180 Sınıf A ve 20 Sınıf B örneği olmasını sağlar. Yani, her parçanın içindeki sınıf oranı (%90 A, %10 B) korunur.

[Scikit-Learn/GridSearchCV Dokumantasyonuna gitmek icin tiklayiniz](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html)

In [16]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold

In [17]:
cv =StratifiedKFold() #icerisindeki cv default=5'dir

### GridSearchCV() icerisine "__estimator__--> verilecek model", "__param_grid__--> deneyecegi parametreler", "__cv__--> koyulacaak cv", "__scoring__--> bu en iyi optimizasyonu __neye__ gore bulacak"

In [18]:
grid = GridSearchCV(estimator=model, param_grid= parametreler, cv=cv, scoring="accuracy") #scoring kismina recall, f1 gibi degerler de verebiliriz

In [19]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'libliner', 'lbfgs', 'sag',
                                    'saga', 'newton-cholesky']},
             scoring='accuracy')

In [20]:
import warnings
warnings.filterwarnings("ignore")

In [21]:
grid.fit(X_train, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 1, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'libliner', 'lbfgs', 'sag',
                                    'saga', 'newton-cholesky']},
             scoring='accuracy')

In [22]:
print(grid.best_params_,"\n") #en iyi parametreler neymis

print(grid.best_score_, "\n") #en iyi accuracy skoru neymis


{'C': 0.1, 'penalty': 'l2', 'solver': 'newton-cg'} 

0.9214285714285715 



In [23]:
y_pred = grid.predict(X_test)

In [24]:
score = accuracy_score(y_pred, y_test)
print("score: ", score,"\n")

print(classification_report(y_test, y_pred))

print("confusion_matrix: \n",confusion_matrix(y_test, y_pred))

score:  0.92 

              precision    recall  f1-score   support

           0       0.90      0.94      0.92       145
           1       0.94      0.90      0.92       155

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

confusion_matrix: 
 [[136   9]
 [ 15 140]]


### Random Search CV

In [25]:
from sklearn.model_selection import RandomizedSearchCV

### Grid Search CV, denemek istediğiniz her bir hiperparametre değerinin tüm olası kombinasyonlarını sistematik bir şekilde denerken, Random Search CV, belirlediğiniz aralıklardan rastgele kombinasyonlar seçerek dener.<br><br>__Hiperparametre Uzayını Tanımlama__: Optimizasyon yapmak istediğiniz hiperparametreler ve her biri için denemek istediğiniz değer aralıklarını veya dağılımlarını belirlersiniz.-->ornegin: C=[0.1-100] arasi<br><br>__Rastgele Kombinasyon Seçimi__: Belirlediğiniz aralıklardan, denemek istediğiniz sayıda rastgele kombinasyon seçersiniz. Örneğin, 100 kombinasyon denemeye karar verirseniz, algoritma bu aralıklardan 100 rastgele kombinasyon seçer.

### __Random Search CV__ ise, özellikle optimizasyon yapacağınız hiperparametre sayısının çok olduğu ve sınırlı bir zamanınız olduğu durumlarda daha verimlidir. Pratikte, Grid Search'e göre daha kısa sürede daha iyi veya benzer sonuçlar verdiği sıkça görülmüştür. Bu yüzden büyük projelerde genellikle Random Search tercih edilir.

In [26]:
model_random= LogisticRegression()

In [27]:
random_cv = RandomizedSearchCV(estimator= model_random, param_distributions=parametreler, cv=5, n_iter=10, scoring="accuracy")
#n_iter-->denedigi random sayisi ,,,,, 

In [28]:
random_cv.fit(X_train, y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'libliner',
                                                   'lbfgs', 'sag', 'saga',
                                                   'newton-cholesky']},
                   scoring='accuracy')

In [29]:
print(random_cv.best_params_, "\n", "score: ", random_cv.best_score_)

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 0.1} 
 score:  0.9214285714285715


In [30]:
y_pred2 = random_cv.predict(X_test)

In [31]:
score = accuracy_score(y_pred2, y_test)
print("score: ", score,"\n")

print(classification_report(y_test, y_pred2))

print("confusion_matrix: \n",confusion_matrix(y_test, y_pred2))

score:  0.92 

              precision    recall  f1-score   support

           0       0.90      0.94      0.92       145
           1       0.94      0.90      0.92       155

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

confusion_matrix: 
 [[136   9]
 [ 15 140]]
